# Runs Bazel tests for DeepMind Lab

env:
  - PY="py2"
  - PY="py3"

sudo: true

language: c++

compiler:
  - clang
  - gcc

cache: pip

addons:
  apt:
    packages:
      - libffi-dev
      - gettext
      - freeglut3-dev
      - libsdl2-dev
      - libosmesa6-dev

before_install:
  - declare -r -A PIP=(["py2"]="2.7.14/bin/pip" ["py3"]="3.6.3/bin/pip3") &&
    sudo -H /opt/python/${PIP[${PY}]} install --upgrade pip &&
    sudo -H /opt/python/${PIP[${PY}]} install numpy Pillow
  - declare -r -A PYINCDIR=(["py2"]="2.7.14/include/python2.7" ["py3"]="3.6.3/include/python3.6m") &&
    declare -r -A PYLIBDIR=(["py2"]="2.7.14/lib/python2.7" ["py3"]="3.6.3/lib/python3.6") &&
    sed python.BUILD -i -e "s#PYINCDIR#${PYINCDIR[${PY}]}#g" -e "s#PYLIBDIR#${PYLIBDIR[${PY}]}#g"
  - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
  - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - sudo add-apt-repository -y ppa:webupd8team/java
  - sudo apt-get update
  - echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  - echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
  - sudo apt-get install bazel

script:
  - declare -r -A PYBIN=(["py2"]="2.7.14/bin/python2.7" ["py3"]="3.6.3/bin/python3.6") &&
    declare -r PYPATH="/opt/python/${PYBIN[${PY}]}" &&
    case "${CXX}" in
      "g++")     bazel test --python_path=${PYPATH} --show_progress_rate_limit=20 -c opt --copt=-Wno-sign-compare --copt=-Wno-maybe-uninitialized //... ;;
      "clang++") bazel test --python_path=${PYPATH} --show_progress_rate_limit=20 -c opt --copt=-Wno-sign-compare --copt=-Wno-uninitialized --cxxopt=-std=c++11 //... ;;
    esac
